/**
 * admin-review — the marketing review/approval desk (served at admin.theplot.tv).
 *
 * One token-gated page listing the week's generated posts. Per post you can edit
 * the copy inline and Approve (-> status 'approved', the daily push sends it to
 * Buffer on its day) or Reject (-> 'vetoed', never sent). Deliberately tiny:
 * server-rendered HTML, form POSTs back to itself, no framework, no client JS.
 *
 * Auth: ?key=<ADMIN_TOKEN> once; we set a cookie so navigation/forms keep working.
 */
import { createClient } from 'npm:@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ADMIN_TOKEN = Deno.env.get('ADMIN_TOKEN') ?? '';

// Statuses that appear on the desk (generated by the batch, awaiting a decision).
const REVIEWABLE = ['needs_review', 'copy_ready', 'generated'];

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
const mediaUrl = (p: string) => `${SUPABASE_URL}/storage/v1/object/public/marketing/${p}`;
const fmtDay = (iso: string) =>
  new Date(iso).toLocaleDateString('en-AU', { weekday: 'long', day: 'numeric', month: 'short', timeZone: 'Australia/Sydney' });

const cookieToken = (req: Request) =>
  (req.headers.get('cookie') || '').split(/;\s*/).find((c) => c.startsWith('admin_token='))?.slice('admin_token='.length);

const authed = (req: Request, url: URL) =>
  ADMIN_TOKEN.length > 0 && (url.searchParams.get('key') === ADMIN_TOKEN || cookieToken(req) === ADMIN_TOKEN);

const shell = (body: string) => `<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>PLOT review desk</title>
<style>
  :root { --ink:#0c0c0c; --mut:#6b6b70; --line:#e5e3e0; --pink:#E05578; --teal:#0F6E56; }
  * { box-sizing:border-box; } body { font-family:'DM Sans',system-ui,sans-serif; color:var(--ink); max-width:880px; margin:0 auto; padding:28px 18px 80px; }
  h1 { font-size:1.4rem; margin:0 0 4px; } .sub { color:var(--mut); font-size:.9rem; margin:0 0 24px; }
  .post { border:1px solid var(--line); border-radius:14px; padding:18px; margin-bottom:22px; }
  .meta { display:flex; gap:10px; align-items:baseline; margin-bottom:12px; }
  .kind { font-weight:600; } .day { color:var(--mut); font-size:.85rem; }
  .imgs img { height:150px; border-radius:8px; margin:0 8px 8px 0; vertical-align:top; }
  label { display:block; font-size:.72rem; text-transform:uppercase; letter-spacing:.06em; color:var(--mut); margin:12px 0 4px; }
  textarea, input { width:100%; font:inherit; font-size:.92rem; border:1px solid var(--line); border-radius:8px; padding:9px; resize:vertical; }
  .row { display:flex; gap:10px; margin-top:16px; }
  button { font:inherit; font-weight:600; border:0; border-radius:9999px; padding:10px 20px; cursor:pointer; }
  .save { background:#f0efea; color:var(--ink); } .approve { background:var(--teal); color:#fff; } .reject { background:#fff; color:var(--pink); border:1px solid var(--pink); }
  .empty { color:var(--mut); padding:40px 0; } .flash { background:#eef7f0; color:var(--teal); padding:10px 14px; border-radius:8px; margin-bottom:18px; font-size:.9rem; }
</style></head><body>${body}</body></html>`;

const field = (label: string, name: string, value: string, rows = 2) =>
  `<label>${label}</label><textarea name="${name}" rows="${rows}">${esc(value)}</textarea>`;

// deno-lint-ignore no-explicit-any
const postForm = (p: any, key: string) => {
  const c = p.copy || {};
  const media = (p.media || []) as { portrait_path?: string }[];
  const imgs = media.map((m) => (m.portrait_path ? `<img src="${esc(mediaUrl(m.portrait_path))}" alt="">` : '')).join('');
  const body = Array.isArray(c.page_body) ? c.page_body.join('\n\n') : (c.page_body || '');
  const tags = Array.isArray(c.hashtags) ? c.hashtags.join(', ') : '';
  const isConvo = p.post_type === 'conversation';
  return `<form class="post" method="POST" action="/">
    <input type="hidden" name="key" value="${esc(key)}">
    <input type="hidden" name="id" value="${esc(p.id)}">
    <div class="meta"><span class="kind">${esc(p.post_type.replace(/_/g, ' '))}</span><span class="day">${esc(fmtDay(p.scheduled_for))}</span></div>
    <div class="imgs">${imgs}</div>
    ${field('X', 'x', c.x || '')}
    ${isConvo ? '' : field('Instagram', 'instagram', c.instagram || '', 3)}
    ${isConvo ? '' : field('Threads', 'threads', c.threads || '')}
    ${isConvo ? '' : `<label>Hashtags (comma separated)</label><input name="hashtags" value="${esc(tags)}">`}
    ${isConvo ? '' : field('Article title', 'page_title', c.page_title || '')}
    ${isConvo ? '' : field('Article body (blank line between paragraphs)', 'page_body', body, 8)}
    <div class="row">
      <button class="save" name="action" value="save">Save edits</button>
      <button class="approve" name="action" value="approve">Approve</button>
      <button class="reject" name="action" value="reject">Reject</button>
    </div>
  </form>`;
};

Deno.serve(async (req) => {
  const url = new URL(req.url);
  if (!authed(req, url)) {
    return new Response(shell('<h1>PLOT review desk</h1><p class="empty">Add <code>?key=…</code> to access.</p>'),
      { status: 401, headers: { 'content-type': 'text/html; charset=utf-8' } });
  }
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });
  const setCookie = url.searchParams.get('key') === ADMIN_TOKEN
    ? { 'set-cookie': `admin_token=${ADMIN_TOKEN}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000` } : {};

  let flash = '';
  if (req.method === 'POST') {
    const form = await req.formData();
    const id = String(form.get('id') || '');
    const action = String(form.get('action') || '');
    if (id && action === 'reject') {
      await supabase.from('marketing_posts').update({ status: 'vetoed', updated_at: new Date().toISOString() }).eq('id', id);
      flash = 'Rejected.';
    } else if (id) {
      const copyPatch: Record<string, unknown> = {
        x: String(form.get('x') || ''),
      };
      if (form.has('instagram')) copyPatch.instagram = String(form.get('instagram') || '');
      if (form.has('threads')) copyPatch.threads = String(form.get('threads') || '');
      if (form.has('hashtags')) copyPatch.hashtags = String(form.get('hashtags') || '').split(',').map((s) => s.trim().replace(/^#/, '')).filter(Boolean);
      if (form.has('page_title')) copyPatch.page_title = String(form.get('page_title') || '');
      if (form.has('page_body')) copyPatch.page_body = String(form.get('page_body') || '').split(/\n\s*\n/).map((s) => s.trim()).filter(Boolean);
      // Merge edits onto the existing copy.
      const { data: cur } = await supabase.from('marketing_posts').select('copy').eq('id', id).single();
      const merged = { ...(cur?.copy || {}), ...copyPatch };
      const patch: Record<string, unknown> = { copy: merged, updated_at: new Date().toISOString() };
      if (action === 'approve') patch.status = 'approved';
      await supabase.from('marketing_posts').update(patch).eq('id', id);
      flash = action === 'approve' ? 'Approved — it will post on its day.' : 'Saved.';
    }
  }

  const { data: posts } = await supabase
    .from('marketing_posts')
    .select('id, post_type, scheduled_for, copy, media, status')
    .in('status', REVIEWABLE)
    .order('scheduled_for');

  const key = url.searchParams.get('key') || cookieToken(req) || '';
  const list = (posts || []).length
    ? (posts || []).map((p) => postForm(p, key)).join('')
    : '<p class="empty">Nothing awaiting review. The weekly batch drops the next week’s posts here.</p>';
  const html = shell(
    `<h1>PLOT review desk</h1><p class="sub">${(posts || []).length} post(s) awaiting review</p>${flash ? `<div class="flash">${esc(flash)}</div>` : ''}${list}`);
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', ...setCookie } });
});
