export const BROADCAST_GUIDE = {
  kicker: 'Free-to-air television',
  chooseMarket: 'Choose your TV market in Settings to see local listings.',
  notConfigured: 'Choose a TV market',
  accountNote: 'Your broadcast region and channels sync across your devices. Changing market resets your channel selection.',
  preferencesError: 'Could not load your broadcast settings.',
  saveError: 'Could not save your broadcast settings. Your changes are still here. Try again.',
  saving: 'Saving broadcast settings…',
  country: 'Country', market: 'TV market',
  countries: { AU: 'Australia', NZ: 'New Zealand', US: 'United States', CA: 'Canada', GB: 'United Kingdom' },
  coverage: { capital: 'Capital-city broadcast feed. Reception outside this area may differ.', national: 'National channel feed. Times are shown in the listed timezone.', starter: 'Starter lineup of selected local stations. More channels and areas are coming.', unavailable: 'This source is currently unavailable. We will show listings when it returns.', unsupported: 'Listings are not available for this area yet. We will not substitute another area’s channels.' },
  unsupported: 'Your local guide is not available yet.',
  chooseArea: 'Change your TV market in Settings if a supported area matches where you watch.',
  providerLabel: 'Schedule source', missingChannels: n => `${n} selected channels have no listings for this date.`,
  settings: 'Settings', saveRegion: 'Save region', regionSaved: 'Broadcast region saved.',
  storageError: 'Your browser could not save this setting. Please enable site storage and try again.',
  changeRegion: 'Change', backToGuide: 'Back to Guide',
  title: 'Guide', subtitle: 'Free-to-air TV',
  setup: {
    title: 'A little less scrolling.',
    titleEnd: 'A little more watching.',
    description: 'Find what’s on now and what’s worth staying in for. Choose your area to bring your local free-to-air channels together in one guide.',
    countryPlaceholder: 'Choose your country',
    area: 'City or region',
    areaPlaceholder: 'Choose your area',
    submit: 'Show my guide',
    hint: 'Change your area anytime.',
  },
  preview: 'Development preview · Free-to-air television',
  previewNote: 'Local feed evaluation. Channel choices are saved on this device only.',
  region: 'Broadcast region', regionShort: 'Region', regionNote: 'Capital-city feeds for now. Regional reception areas still need verification.',
  channels: 'My channels', allChannels: 'Select all', noChannels: 'Clear selection',
  apply: 'Apply channels', cancel: 'Cancel', today: 'Today', now: 'On now', allDay: 'Full day',
  comingUp: 'Coming up', week: 'Week', editChannels: 'Edit channels', done: 'Done',
  jumpToTime: 'Jump to time', chooseTime: 'Choose a time',
  ends: t => `Ends ${t}`, nothingOnNow: 'Nothing on your channels right now.',
  channelsCount: n => `My channels · ${n}`, of: (n, total) => `${n} of ${total}`,
  search: 'Find a programme', empty: 'No programmes match this view.',
  noneSelected: 'Choose some channels to build your guide.',
  unavailable: 'Listings are unavailable for this region.',
  unavailableBody: 'Your channel choices are kept. Try again when the schedule is available.',
  stale: 'These listings may be out of date.', cached: 'Refresh failed. Showing the last loaded listings.',
  loading: 'Loading your guide…', retry: 'Try again', close: 'Close programme details',
  noDescription: 'No programme description supplied.',
  source: 'Schedule: Matt Huisman', noSchedule: 'No listings supplied',
  updated: 'Downloaded', timezone: 'Times shown in',
  count: n => `${n} channels selected`,
};
