// Shared copy for the History page. Lives in @plot/core/copy so mobile can pick
// up the same words when it gets its own History screen.

export const HISTORY_VIEW = {
  title: 'History',
  subtitle: 'Everything you have marked watched, newest first',
  searchPlaceholder: 'Search your history',
  yearSoFar: (year) => `${year} so far`,
  yearCardTitle: (year) => `${year}`,
  titles: 'titles',
  watchingMovies: 'in movies',
  yourAverage: 'your average',
  yourNight: 'your night',
  daysWithAWatch: (n) => `${n} ${n === 1 ? 'day' : 'days'} with a watch`,
  bestStreak: 'Best streak',
  crowdHeading: 'You vs the crowd',
  crowdDisagreements: 'Your biggest disagreements with TMDB',
  crowdNeedsRatings: 'Rate a few titles and this fills in.',
  peopleHeading: 'You keep coming back to',
  peopleNeedsMore: 'Nobody twice yet. Give it a few more titles.',
  loadingInsights: 'Working out your year',
  filterStatus: 'Status',
  filterReviewed: 'Reviewed',
  filterDidntFinish: "Didn't finish",
  emptyTitle: 'Nothing watched yet',
  emptyBody: 'Your watch history will appear here. Search for a title and mark it as watched to get started.',
  noMatchesTitle: 'No matches',
  noMatchesBody: 'Nothing in your history matches these filters.',
  reviewed: 'You wrote a review',
  didNotFinish: 'DNF',
  openTitle: (title) => `View details for ${title}`,
  monthTitles: (n) => `${n} ${n === 1 ? 'title' : 'titles'}`,
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
};
