// Shared plan preview for web and mobile. Planned features are never shown as live entitlements.
export const PLANS_PAGE = {
  back: '← Back',
  eyebrow: 'plot Premium',
  title: 'Less deciding. More watching.',
  lede: 'A movie that fits your evening. A new episode you won’t miss. Something you both want to watch. Make more of the time you set aside for it.',
  comingSoon: 'Coming soon',
  pendingValidation: 'Pending validation',
  plannedFree: 'Free, coming soon',
  previewAction: 'Explore Premium',
  upgradeAction: 'Upgrade to Premium',
  checkoutMessage: 'plot Premium is coming soon. Checkout is not open yet. There is nothing to pay today.',
  free: {
    name: 'Free',
    perpetual: 'forever',
    tagline: 'Your everyday watching, all in one place.',
    yourCurrentPlan: 'Your current plan',
    includedWithPremium: 'Included with Premium',
    getStartedFree: 'Get started free',
  },
  premium: {
    name: 'Premium',
    tagline: 'For the evenings you want to spend watching.',
    price: 'A$5',
    period: '/month',
    annual: 'or A$40/year',
    priceSummary: 'A$5/month or A$40/year',
    availability: 'Premium is in the works. These features are a preview of what’s coming.',
    manageSubscription: 'Manage subscription',
    opening: 'Opening…',
  },
  comparison: {
    title: 'Compare every feature',
    featureHeader: 'Feature',
    freeHeader: 'Free',
    premiumHeader: 'Premium',
    included: 'Included',
    notIncluded: 'Not included',
    unlimited: 'Unlimited',
  },
  freeFeatures: [
    { id: 'tracking', label: 'Movie and TV tracking, watch history and episode progress' },
    { id: 'watchlist', label: 'Watchlist, ratings and reviews' },
    { id: 'notes', label: 'Private watchlist notes',
      description: 'Keep a private reminder of why you saved a title, separate from your reviews.' },
    { id: 'customLists', label: 'Up to five custom lists',
      description: 'Create up to five custom lists for free.' },
    { id: 'discovery', label: 'Discovery, recommendations, search and where to watch' },
    { id: 'statistics', label: 'Your viewing statistics' },
    { id: 'calendar', label: 'In-app release calendar and downloadable calendar snapshot' },
    { id: 'social', label: 'Follow friends and share profiles' },
    { id: 'participation', label: 'Join collaborative lists and shared watch sessions', planned: true,
      description: 'Join a Premium host for free. Only the person hosting needs Premium.' },
    { id: 'imports', label: 'Existing imports and data exports' },
  ],
  customLists: (cap) => `Currently up to ${cap} custom lists`,
  premiumFeatures: [
    { id: 'watchTogether', label: 'Find something you both want to watch', highlight: true,
      description: 'Find the overlap in your watchlists, then choose together. Invite friends to a shared list so everyone can add their ideas. They can join for free.' },
    { id: 'filmPicker', label: 'Tonight’s movie picker', highlight: true,
      description: 'Choose how much time you have and the services you use. Get a shortlist for tonight, or let a random pick make the decision.' },
    { id: 'collaborativeLists', label: 'Create collaborative lists', highlight: true,
      description: 'Build your next movie night together. Invite friends to add titles, even when they use Free.' },
    { id: 'unlimitedLists', label: 'Unlimited custom lists', highlight: true,
      description: 'A list for every mood, theme and movie marathon, with no limit on how many you create.' },
    { id: 'smartLists', label: 'Smart lists, including new discoveries',
      description: 'Save filter rules that automatically update your lists, including discoveries beyond your saved titles.' },
    { id: 'releaseAlerts', label: 'Movie and episode release notifications',
      description: 'Get a notification when the movies and episodes you are following are released.' },
    { id: 'calendarSubscription', label: 'Live calendar subscription',
      description: 'Keep upcoming releases updated in your calendar app automatically.' },
    { id: 'peopleAlerts', label: 'Actor and director release alerts',
      description: 'Follow the people you love watching and hear about their new releases.' },
    { id: 'seasonReady', label: 'Whole-season-ready alerts',
      description: 'Know when every episode is verified available on your selected services in your region. Airing dates alone do not qualify.' },
    { id: 'widgets', label: 'Configurable iOS widgets',
      description: 'See upcoming releases and what to watch next on your Home Screen, with artwork or compact layouts.' },
    { id: 'leavingSoon', label: 'Leaving-my-service-soon alerts', pendingValidation: true,
      description: 'An alert before a title leaves your service. Subject to confirming reliable departure-date coverage.' },
  ],
  storyIntro: 'A little help getting to the good part.',
  previewLabel: 'Planned for Premium',
  compareAction: 'See everything included',
  freeTitle: 'Your watching life. Still free.',
  freeDescription: 'Keep tracking, discovering and looking back at what you’ve watched. Your existing viewing stats, recommendations and where-to-watch information stay in Free.',
  freePlanned: 'Free includes private watchlist notes and five custom lists. Joining a Premium host’s shared lists and watch sessions is coming soon.',
  freeGroups: ['Track movies, shows and episodes', 'Keep your ratings, reviews and stats', 'Find where to watch and what’s next'],
  planSummary: ['Pick a movie by runtime and service', 'Follow actors and directors for new releases', 'Choose together and share lists', 'Build unlimited and smart lists'],
  stories: [
    { id: 'picker', kicker: 'FOR TONIGHT', title: 'Something you can actually watch tonight.',
      description: 'An hour and a half to spare? Narrow the choices by runtime and the services you use. Pick from a shortlist, or let plot choose at random.',
      detail: 'Tonight’s movie picker', example: ['90 minutes to spare', 'Your streaming services', 'A shorter shortlist'],
      caption: 'Your time + your services → tonight’s options' },
    { id: 'alerts', kicker: 'FOR WHAT’S NEXT', title: 'Their next thing. Your next watch.',
      description: 'Love an actor? Always make time for a certain director? Follow them and hear when their next movie or show is on the way. Get release reminders and keep upcoming releases in your calendar, too.',
      detail: 'Release alerts · People to follow · Live calendar', example: ['New movie releases', 'The next episode', 'Actors and directors you follow'],
      caption: 'The releases you care about, easier to follow' },
    { id: 'together', kicker: 'FOR MOVIE NIGHT', title: 'Find the overlap. Put something on.',
      description: 'See what’s on both your watchlists. Create a shared list for date nights, housemates or the group chat. Only the host needs Premium.',
      detail: 'Watchlist matches · Collaborative lists', example: ['Your watchlist', 'Their watchlist', 'Something you both saved'],
      caption: 'Friends can join with a free account' },
    { id: 'lists', kicker: 'FOR ALL YOUR IDEAS', title: 'Give every kind of night its own list.',
      description: 'Make as many lists as you like. Save rules for smart lists that keep finding matches, including movies and shows you haven’t saved yet.',
      detail: 'Unlimited lists · Smart lists', example: ['A quick weeknight watch', 'The Sunday movie club', 'New finds that fit your rules'],
      caption: 'Less sorting. More to look forward to.' },
  ],
  faqTitle: 'Before you ask',
  faqs: [
    { q: 'Can I upgrade now?', a: 'Not yet. Premium will be A$5/month or A$40/year. The upgrade button shows a coming-soon message; it does not start a payment or a trial.' },
    { q: 'What happens to Free?', a: 'Your current free features stay available. Private watchlist notes are included in Free, separate from public reviews.' },
    { q: 'Can my friends join without Premium?', a: 'Yes. Joining a Premium host’s collaborative lists and shared watch sessions is planned for Free. Premium is only needed to create or host them.' },
    { q: 'How many lists are included in Free?', a: 'Free includes up to five custom lists.' },
    { q: 'Does plot play the movie for us?', a: 'No. Shared watch sessions help you choose a title together. You watch it on your streaming service; plot does not stream or sync playback.' },
    { q: 'Are these alerts available now?', a: 'No. These are planned Premium features. Whole-season alerts need verified availability for every episode on your selected service, and departure alerts are still pending data validation.' },
  ],
  terms: 'Terms',
  privacy: 'Privacy',
};
