export const TRACKING = {
  sourceSelected: 'Server and profile selected. Ready to import.',
  title: 'Watch tracking',
  description: 'One-time Trakt history and watchlist imports are free. Automatic updates require Premium. Trakt imports what Trakt already knows; it does not connect your streaming accounts.',
  connect: 'Connect Trakt for migration',
  connectPlex: 'Connect Plex (Premium)',
  authExpired: 'Plex sign-in expired. Connect again to retry.',
  authPopupBlocked: 'Allow a new browser window to connect Plex, then retry.',
  authFailed: 'Could not confirm Plex sign-in. Check your connection and retry.',
  authorizing: 'Waiting for Plex approval…',
  chooseSource: 'Choose Plex server and profile',
  sourceError: 'Could not load or select the Plex profile. Check server remote access and retry.',
  selectedSource: (source) => `Selected: ${source.name}, ${source.profileName}`,
  sync: 'Sync selected Plex profile',
  import: 'Import Trakt history and watchlist',
  enableAutomatic: 'Enable automatic updates',
  disableAutomatic: 'Pause automatic updates',
  enableOutgoing: 'Allow outgoing watchlist changes',
  disableOutgoing: 'Stop outgoing watchlist changes',
  outgoingDescription: 'Incoming activity only. Outgoing watchlist updates are not available in this pilot.',
  review: 'Possible duplicate watch',
  reviewDetails: (event) => `${event.source}, ${event.watched_on || 'unknown date'}${event.episode_number != null ? `, S${event.season_number} E${event.episode_number}` : ''}`,
  keep: 'Keep as a separate watch',
  skip: 'Skip this watch',
  refresh: 'Refresh tracking status',
  resume: 'Retry or resume job',
  cancel: 'Cancel job',
  disconnect: 'Disconnect and retain imported data',
  loading: 'Loading tracking status…',
  error: 'Could not update tracking. Check your connection and retry. Premium is required for automatic updates.',
  never: 'No successful sync yet',
  success: (date) => `Last successful sync: ${date}`,
  counts: (job) => `${job.imported} imported, ${job.duplicates} already imported, ${job.skipped} skipped, ${job.review_count || 0} flagged for review`,
  statuses: { queued: 'Queued', running: 'Syncing', retry_wait: 'Waiting to retry', paused: 'Paused', succeeded: 'Complete', partial: 'Partially imported', failed: 'Needs attention', cancelled: 'Cancelled' },
};
