// Watch together (Premium). Shared by web and mobile. Design and agreed rules:
// docs/design/watch-together/README.md. Avoid "movie night": it may be a show,
// and it may not be night.

export const WATCH_TOGETHER = Object.freeze({
  navLabel: 'Watch together',

  hub: {
    title: 'Watch together',
    decideTitle: 'Decide what to watch',
    decideBody: 'Choose who you’re watching with. Plot finds what you’ve all saved.',
    whosWatching: 'Who’s watching?',
    requests: 'Requests',
    requestsSummary: (incoming, outgoing) => {
      const parts = [];
      if (incoming) parts.push(`${incoming} waiting for you`);
      if (outgoing) parts.push(`${outgoing} sent`);
      return parts.join(' · ');
    },
    partners: 'People you watch together with',
    invite: 'Invite',
    bothSaved: (n) => `${n} on both watchlists`,
    noPartnersTitle: 'Nobody here yet.',
    noPartnersBody: 'Invite someone to see what you’ve both saved.',
    suggested: 'Suggested',
    suggestedBody: 'People you might watch together with',
    freeTitle: 'Get Premium to watch together',
    lockedNote: 'One of you needs Premium to decide together',
  },

  // What someone with nobody to watch with yet sees at /together, Free or not.
  start: {
    overlapsTitle: 'You already have things in common',
    overlapsBody: 'People you follow, and how many titles you’ve both saved. Inviting is free.',
    inCommon: (n) => `${n} in common`,
    countLater: 'Shows once they accept',
    pitchTitle: 'Find something you both want to watch',
    pitchBody: 'Pair up with a friend and Plot shows what’s on both your watchlists. Swipe through them together until you both say yes.',
    getPremium: 'Get Premium',
    premiumNote: (price) => `One of you needs Premium to decide together. ${price}.`,
    seeItTitle: 'See it in action',
    seeItBody: 'What it looks like with a friend, and a quick try with your own watchlist.',
    example: 'Example',
    examplePair: 'You and Sam',
    exampleCount: '12 on both watchlists',
    exampleMatch: 'You’re both in: Past Lives',
    exampleMatchNote: 'Matched while deciding with Sam',
    demoHeading: 'Deciding with Sam',
    demoNote: 'Five titles from your watchlist. Sam is an example partner.',
    demoEmpty: 'Save a few titles to your watchlist to try it.',
    demoDoneTitle: 'You’re both in',
    demoDoneBody: 'That’s how it works with a friend. Invite someone and Plot finds what you’ve both saved.',
    demoAgain: 'Try again',
    howTitle: 'How it works',
    steps: [
      { title: 'Invite someone', body: 'They get a request. Inviting and joining are free.' },
      { title: 'See what you’ve both saved', body: 'Only the titles on both your watchlists.' },
      { title: 'Swipe together', body: 'Yes or no on each one until you match.' },
    ],
    gotInviteTitle: 'Got an invite?',
    gotInviteBody: 'Accepting is free. You can decide together as long as one of you has Premium.',
  },

  // Reusable invite links (/watch-with/:username/:key).
  link: {
    kicker: 'Invite link',
    title: 'Know who you want to watch with?',
    body: 'Send your link in any app. They can open it without an account, and it’s free for them to join.',
    previewTitle: (name) => `Watch together with ${name}`,
    share: 'Share link',
    copy: 'Copy',
    copied: 'Copied',
    shareText: 'Find something we both want to watch on Plot.',
    inviteTitle: 'Or send your invite link',
    inviteBody: 'Works in any app, even if they’re not on Plot yet.',
    reset: 'Reset invite link',
    resetNote: 'Links you’ve already sent stop working.',
  },

  landing: {
    title: (name) => `${name} wants to watch together`,
    titleNewLead: (name) => `${name} wants to watch together on`,
    body: 'Accept to see the titles you’ve both saved and decide what to watch.',
    bodyNoPremium: (name) => `One of you needs Premium to decide together. ${name} can upgrade, or you can.`,
    bodyNew: (name) => `Plot keeps track of what you watch. Join for free, save a few titles, and see what you and ${name} both want to watch.`,
    accept: 'Accept',
    notNow: 'Not now',
    imIn: (name) => `Tell ${name} I’m in`,
    imInNote: 'This saves your yes. It starts as soon as either of you has Premium.',
    acceptNote: (name) => `Accepting doesn’t follow ${name}. You can stop any time.`,
    joinLead: 'Join',
    joinTail: 'for free',
    haveAccount: 'I have an account',
    newNote: (name) => `After you sign up, ${name}’s invite is waiting for you.`,
    selfTitle: 'This is your invite link',
    selfBody: 'Send it to someone you want to watch with.',
    pairedTitle: (name) => `You and ${name} watch together`,
    invalidTitle: 'This link doesn’t work anymore',
    invalidBody: 'Ask for a new one. It may have been reset.',
  },

  locked: {
    title: 'One of you needs Premium to decide together',
    body: (name) => `${name} can upgrade, or you can.`,
  },

  requests: {
    title: 'Requests',
    incoming: 'Waiting for you',
    outgoing: 'Sent',
    wantsTo: 'wants to watch together',
    sent: 'Request sent',
    review: 'Review',
    decline: 'Decline',
    cancel: 'Cancel request',
    none: 'No requests right now.',
  },

  accept: {
    title: (name) => `Watch together with ${name}?`,
    willSee: (name) => `${name} will see`,
    wontSee: (name) => `${name} won’t see`,
    seesOverlap: 'Titles that are on both your watchlists',
    seesPicks: 'Your picks when you decide together',
    hidesRest: 'The rest of your watchlist, unless you turn it on below',
    hidesPrivateLists: 'Any lists you’ve set to private',
    hidesNotes: 'Your private notes',
    shareFull: 'Also share my full watchlist',
    shareFullBody: (name) => `Lets ${name} see what else you’d like to watch. Your profile is private, so your watchlist stays hidden unless you turn this on.`,
    accept: 'Accept',
    notNow: 'Not now',
    foot: (name) => `You can stop any time in Settings. ${name} isn’t told if you decline.`,
  },

  tile: {
    kicker: 'Watch together',
    requestSent: 'Request sent',
    watchingTogether: 'Watching together',
    onBoth: 'titles on both your watchlists',
    privateTitle: (name) => `${name}’s watchlist is private`,
    waitingTitle: (name) => `Waiting for ${name}`,
    freeFoot: 'One of you needs Premium to decide together.',
    publicBody: (name) => `${name} gets a request to accept. Once they do, you can choose from what you’ve both saved.`,
    privateBody: (name) => `Send a request. If ${name} accepts, you’ll see the titles you’ve both saved.`,
    inviteAction: (name) => `Invite ${name} to watch together`,
    joinFree: (name) => `${name} can join for free.`,
    pendingBody: (name) => `Watch together request sent. ${name} needs to accept before you can choose together.`,
    pendingFoot: 'Requests expire after 30 days.',
    incomingBody: (name) => `${name} wants to watch together.`,
    incomingAction: 'Review request',
    pairedBody: (name) => `You and ${name} are watching together. Choose from what you’ve both saved.`,
    pairedAction: 'See what you both saved',
    pairedFoot: 'Manage in Settings › Privacy',
  },

  overlap: {
    heading: (n) => `${n} ${n === 1 ? 'title' : 'titles'} you’ve both saved.`,
    pair: (name) => `You and ${name}`,
    movies: 'Movies',
    shows: 'Shows',
    show: 'Show',
    filter: 'Filter titles',
    you: 'You',
    everyone: 'everyone',
    group: (names) => `You, ${names.slice(0, -1).join(', ')}${names.length > 1 ? ' and ' : ''}${names[names.length - 1]}`,
    groupHeading: 'What you’ve all saved.',
    groupAction: 'See group matches',
    savedByAll: 'Saved by everyone',
    savedBySome: 'Saved by some of you',
    savedBy: (names) => names.length > 1 ? `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}` : names[0] || '',
    all: 'All',
    topMatch: 'Top match',
    choose: 'Choose this',
    shuffle: 'Shuffle',
    alsoOnBoth: 'Also on both your watchlists',
    emptyTitle: 'Nothing in common yet.',
    emptyBody: (name) => `When you and ${name} save the same title, it shows up here.`,
    notPartners: 'You’re not watching together with this person.',
  },

  session: {
    heading: (name) => `Deciding with ${name}`,
    fromBoth: 'From both your watchlists',
    counter: (n, total) => `${n} of ${total}`,
    choosing: 'Choosing',
    theyAnswered: (n) => `On card ${n}`,
    no: 'Not feeling it',
    yes: 'I’m in',
    bothIn: 'You’re both in',
    matchesSoFar: (n) => `${n} ${n === 1 ? 'match' : 'matches'} so far`,
    seeMatches: 'See matches',
    hideMatches: 'Back to cards',
    matchesTitle: 'Your matches',
    noMatches: 'No matches yet.',
    doneTitle: 'That’s every title.',
    doneBody: (name) => `Waiting for ${name} to finish. Matches show up here.`,
    choose: 'Choose this',
    leave: 'Leave',
    ended: 'This session has ended.',
    startAgain: 'Start again',
    empty: (name) => `You and ${name} don’t have any titles in common yet.`,
    swipeHint: 'Swipe right if you’re in, left if not.',
    start: 'Decide together',
  },

  sharedList: {
    want: (name) => `Want ${name} to add ideas?`,
    make: 'Make a shared list',
    open: 'Open your shared list',
    summary: (name, n) => `${name} · ${n} ${n === 1 ? 'title' : 'titles'}`,
    defaultName: (creator, partner) => `${creator} and ${partner}`,
    sheetTitle: 'Make a shared list',
    name: 'Name',
    startWith: 'Start with',
    startBoth: (n) => `The ${n} ${n === 1 ? 'title' : 'titles'} you’ve both saved`,
    startBothNote: 'A head start from your watchlists',
    startEmpty: 'An empty list',
    startEmptyNote: 'Add titles together from scratch',
    whosOn: 'Who’s on it',
    whosOnNote: 'Only people you watch together with. They can add and remove titles for free.',
    create: 'Create list',
    shared: 'Shared',
    sharedWith: (names) => `Shared with ${names}`,
    addPeople: 'Add people',
    addPeopleNote: 'People you watch together with can join this list.',
    noOneToAdd: 'Everyone you watch together with is already on this list.',
    add: 'Add',
    leave: 'Leave list',
    addedBy: (name) => `Added by ${name}`,
    addedByYou: 'Added by you',
    leaveTitle: (name) => `Leave "${name}"?`,
    leaveBody: 'You can be added back by anyone on the list.',
    error: 'That didn’t work. Try again.',
  },

  savedToo: {
    title: (names) => `Saved by ${names.length > 1 ? `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}` : names[0]} too`,
    one: 'On both your watchlists',
    many: 'Decide what to watch together',
  },

  invite: {
    title: 'Invite to watch together',
    body: 'They get a request to accept. It’s free to join.',
    search: 'Search by name or @username',
    suggested: 'Suggested',
    invite: 'Invite',
    sent: 'Request sent',
    noSuggestions: 'No suggestions right now. Search for someone you follow.',
  },

  settings: {
    title: 'Watch together',
    description: 'Who can ask to watch together with you, and who you watch with.',
    whoCanRequest: 'Who can send you requests',
    fromProfile: 'Anyone who can see my profile',
    fromFollowing: 'Only people I follow',
    fromNone: 'No one',
    partners: 'Watching together with',
    shareFull: 'Share my full watchlist',
    stop: 'Stop',
    since: (date, n) => `Since ${date} · ${n} in common`,
    stopNote: 'Stopping takes effect straight away. The other person stops seeing your overlap and isn’t notified. Blocking someone also stops watching together.',
    none: 'You’re not watching together with anyone yet.',
  },

  errors: {
    premium_required: 'One of you needs Premium to decide together.',
    not_allowed: 'This person isn’t taking watch together requests from you.',
    generic: 'That didn’t work. Try again.',
  },
});
