// Where share-link og:image tags point.
//
// This replaced the `plot-og` Worker (apps/web/workers/og), which renders the
// branded 1200×630 cards with Satori. That render costs ~25ms of CPU against
// the Cloudflare free plan's 10ms per-request ceiling, so on this account it
// returns 503 `Exceeded CPU Limit` for every card and every share unfurled
// without an image. A CPU kill terminates the isolate, so the Worker cannot
// catch its own failure and substitute anything — the choice has to be made
// here, by the caller, at the point the tag is written.
//
// So: titles use TMDB's own backdrop (always available, CDN-hosted, no render),
// and everything else uses the static card committed at apps/web/public.
// Restoring the branded cards means Workers Paid, not more code here.
//
// The static card is 1200×630; TMDB `w1280` backdrops are 1280×720. Callers
// need the matching pair, so they come back together.
export const STATIC_CARD = { width: 1200, height: 630 };
export const TMDB_BACKDROP = { width: 1280, height: 720 };

/** The branded fallback card. Generated by scripts/generate-app-og-image.mjs. */
export const staticCard = (host) => `https://${host}/og-image.png`;
