import AsyncStorage from '@react-native-async-storage/async-storage';
// Generated by the withStorybook metro transform from main.ts's `stories` glob.
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
