#!/usr/bin/env node
/**
 * Shared footer build step for the marketing site.
 *
 * Single sources of truth: website/_partials/footer.html (markup) and
 * website/_partials/footer.css (styles).
 *
 * Consumers kept in sync from them:
 *   1. Static pages (website/index|about|privacy|terms.html …) — the markup is
 *      injected between the `<!-- footer:start -->` / `<!-- footer:end -->`
 *      markers and committed, so Pages keeps serving raw static files.
 *   2. website/ui.css — the styles are injected between the
 *      `/* footer-css:start … *\/` / `/* footer-css:end *\/` markers, so every
 *      static page and the Storybook story get them from the one stylesheet.
 *   3. The /whats-on and /movie|/tv edge functions (supabase/functions/
 *      marketing-feed, title-page) — markup and styles are emitted as a
 *      generated TS module (footer.generated.ts, FOOTER_HTML + FOOTER_CSS)
 *      that index.ts imports, since a Deno function can't read the partials.
 *
 * Usage:
 *   node scripts/build-footer.mjs          # rewrite/regenerate every consumer
 *   node scripts/build-footer.mjs --check  # verify all are in sync (CI); exit 1 if not
 *
 * On first run a page with no markers has its existing <footer> replaced and
 * wrapped in markers, so it is self-installing.
 *
 * Page-specific spacing around the footer (the homepage's ticker clearance,
 * a page's margin-top) stays in that page's own styles.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(ROOT, 'apps', 'website');
const PARTIAL = join(WEB, '_partials', 'footer.html');
const CSS_PARTIAL = join(WEB, '_partials', 'footer.css');
const UI_CSS = join(WEB, 'ui.css');
const PAGES = [
  'index.html',
  'about.html',
  'privacy.html',
  'terms.html',
  'plans.html',
  'community.html',
  'support.html',
  'taste-match.html',
  'changelog.html',
];
const EDGE_TS = join(ROOT, 'supabase', 'functions', 'marketing-feed', 'footer.generated.ts');
const EDGE_TS_TITLE = join(ROOT, 'supabase', 'functions', 'title-page', 'footer.generated.ts');

const START = '  <!-- footer:start (generated from _partials/footer.html — edit there, then run `npm run footer`) -->';
const END = '  <!-- footer:end -->';

const MARKER_RE = /[^\S\n]*<!-- footer:start\b[\s\S]*?<!-- footer:end -->/;

const CSS_START = '/* footer-css:start (generated from _partials/footer.css — edit there, then run `npm run footer`) */';
const CSS_END = '/* footer-css:end */';
const CSS_MARKER_RE = /\/\* footer-css:start\b[\s\S]*?\/\* footer-css:end \*\//;
const FOOTER_RE = /[^\S\n]*<footer\b[\s\S]*?<\/footer>/;

const check = process.argv.includes('--check');

const footer = readFileSync(PARTIAL, 'utf8').replace(/\s+$/, '');
const block = `${START}\n${footer}\n${END}`;
const css = readFileSync(CSS_PARTIAL, 'utf8').replace(/\s+$/, '');
const cssBlock = `${CSS_START}\n${css}\n${CSS_END}`;

// TS module the edge functions import. Escape so each partial is a safe template literal.
const tsEscape = (text) => text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const tsModule = `// @generated by scripts/build-footer.mjs from website/_partials/footer.html + footer.css
// Do not edit by hand — run \`npm run footer\` to regenerate.
export const FOOTER_HTML = \`
${tsEscape(footer)}
\`;

export const FOOTER_CSS = \`
${tsEscape(css)}
\`;
`;

const drift = [];

function sync(absPath, produce) {
  const rel = relative(ROOT, absPath);
  let src;
  try {
    src = readFileSync(absPath, 'utf8');
  } catch {
    src = null;
  }
  const next = produce(src);
  if (next === null) {
    console.error(`✗ ${rel}: could not locate footer to replace`);
    process.exitCode = 1;
    return;
  }
  if (next === src) {
    console.log(`✓ ${rel}: already in sync`);
    return;
  }
  if (check) {
    drift.push(rel);
    console.error(`✗ ${rel}: out of sync with _partials/footer.html`);
  } else {
    writeFileSync(absPath, next);
    console.log(`• ${rel}: updated`);
  }
}

for (const page of PAGES) {
  sync(join(WEB, page), (src) => {
    if (src === null) return null;
    const rx = MARKER_RE.test(src) ? MARKER_RE : FOOTER_RE;
    return rx.test(src) ? src.replace(rx, block) : null;
  });
}

sync(UI_CSS, (src) => {
  if (src === null || !CSS_MARKER_RE.test(src)) return null;
  return src.replace(CSS_MARKER_RE, cssBlock);
});

sync(EDGE_TS, () => tsModule);
sync(EDGE_TS_TITLE, () => tsModule);

if (check && drift.length) {
  console.error(`\n${drift.length} file(s) out of sync. Run \`npm run footer\` and commit.`);
  process.exit(1);
}

if (!check && !process.exitCode) console.log('done');
