#!/usr/bin/env bash
# Refresh the repo-root .env from injected process-env values.
#
# Vite already prefers process.env over the file (apps/web/vite.config.js
# envDir is the repo root), but marketing/db scripts use `node --env-file=.env`
# and would silently read leftover placeholders if we only set the shell.
#
# Writes only keys that are set in the environment. Required VITE_* vars fall
# back to the same inert placeholders CI uses so `pnpm run dev` / `build` still
# start when secrets have not been injected. Never prints values.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${PLOT_ENV_FILE:-$ROOT/.env}"

umask 077

# dotenv / `node --env-file` do not understand bash `%q`. Write unquoted when
# the value is a typical URL or key; otherwise a double-quoted string.
dotenv_value() {
  local value="$1"
  case "$value" in
    *$'\n'*|*$'\r'*)
      echo "cloud-agent-write-env: refusing multiline value" >&2
      return 1
      ;;
    *[!A-Za-z0-9_./:+@%=-]*)
      value="${value//\\/\\\\}"
      value="${value//\"/\\\"}"
      printf '"%s"' "$value"
      ;;
    *)
      printf '%s' "$value"
      ;;
  esac
}

write_kv() {
  local key="$1"
  local value="${!1-}"
  [ -n "$value" ] || return 0
  printf '%s=%s\n' "$key" "$(dotenv_value "$value")"
}

{
  echo "# Generated by scripts/cloud-agent-write-env.sh — do not commit."

  if [ -n "${VITE_SUPABASE_URL:-}" ]; then
    write_kv VITE_SUPABASE_URL
  else
    echo 'VITE_SUPABASE_URL=https://placeholder.supabase.co'
  fi

  if [ -n "${VITE_SUPABASE_ANON_KEY:-}" ]; then
    write_kv VITE_SUPABASE_ANON_KEY
  else
    echo 'VITE_SUPABASE_ANON_KEY=placeholder-not-a-key'
  fi

  if [ -n "${VITE_TMDB_PROXY_URL:-}" ]; then
    write_kv VITE_TMDB_PROXY_URL
  else
    echo 'VITE_TMDB_PROXY_URL=https://placeholder.invalid'
  fi

  for key in \
    VITE_TURNSTILE_SITE_KEY \
    VITE_PUBLIC_POSTHOG_PROJECT_TOKEN \
    VITE_PUBLIC_POSTHOG_HOST \
    VITE_PUBLIC_POSTHOG_FORCE \
    VITE_TRAKT_CLIENT_ID \
    VITE_AUTH_REDIRECT_BASE_URL \
    VITE_APP_ORIGIN \
    VITE_SHOW_GOOGLE_LOGIN \
    VITE_AMZ_TAG_AU \
    VITE_AMZ_TAG_US \
    VITE_AMZ_TAG_GB \
    VITE_APPLE_AT_TOKEN \
    SUPABASE_URL \
    SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY \
    SUPABASE_DB_URL \
    PLOT_PRODUCTION_DB_PASSWORD \
    PLOT_PRODUCTION_POOLER_HOST \
    TMDB_API_KEY \
    RESEND_API_KEY
  do
    write_kv "$key"
  done

  if [ -n "${VITE_SUPABASE_URL:-}" ] && [ -z "${SUPABASE_URL:-}" ]; then
    printf 'SUPABASE_URL=%s\n' "$(dotenv_value "$VITE_SUPABASE_URL")"
  fi
  if [ -n "${VITE_SUPABASE_ANON_KEY:-}" ] && [ -z "${SUPABASE_ANON_KEY:-}" ]; then
    printf 'SUPABASE_ANON_KEY=%s\n' "$(dotenv_value "$VITE_SUPABASE_ANON_KEY")"
  fi
} > "$DEST"
