// @generated by scripts/build-footer.mjs from website/_partials/footer.html + footer.css
// Do not edit by hand — run `npm run footer` to regenerate.
export const FOOTER_HTML = `
  <footer class="site-footer">
    <div class="footer-inner">
      <div class="footer-top">
        <div class="footer-intro">
          <p class="footer-lede">Everything you've watched.<br>Everything you want to watch.</p>
          <div class="footer-actions">
            <a class="footer-cta" href="https://app.theplot.tv/signup" data-cta="footer">Start your plot</a>
            <a class="footer-login" href="https://app.theplot.tv/login" data-cta="footer">Log in</a>
          </div>
        </div>
        <div class="footer-cols" role="navigation" aria-label="Footer">
          <div class="footer-col">
            <h2 class="footer-heading">Explore</h2>
            <ul>
              <li><a href="/whats-on" data-cta="footer">What's On</a></li>
              <li><a href="/whats-on#newsletter" data-cta="footer">Newsletter</a></li>
              <li><a href="/plans" data-cta="footer">Plans</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h2 class="footer-heading">Company</h2>
            <ul>
              <li><a href="/about" data-cta="footer">About</a></li>
              <li><a href="/community" data-cta="footer">Community</a></li>
              <li><a href="/support" data-cta="footer">Support</a></li>
              <li><a href="/changelog" data-cta="footer">Changelog</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h2 class="footer-heading">Legal</h2>
            <ul>
              <li><a href="/privacy" data-cta="footer">Privacy</a></li>
              <li><a href="/terms" data-cta="footer">Terms</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="footer-copy">&copy; 2026 plot</div>
        <div class="footer-social">
          <a href="https://www.instagram.com/theplottv" target="_blank" rel="noopener" aria-label="plot on Instagram" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1.1" fill="currentColor" stroke="none"/></svg>
          </a>
          <a href="https://www.threads.net/@theplottv" target="_blank" rel="noopener" aria-label="plot on Threads" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M16.05 11.18c-.09-.04-.18-.08-.27-.12-.16-2.93-1.76-4.6-4.45-4.62h-.04c-1.61 0-2.95.69-3.77 1.94l1.48 1.02c.61-.93 1.57-1.13 2.29-1.13h.03c.9.01 1.57.27 2 .78.31.37.52.88.63 1.52-.81-.14-1.69-.18-2.63-.13-2.64.15-4.34 1.69-4.22 3.83.06 1.08.6 2.02 1.51 2.64.77.52 1.77.78 2.8.72 1.37-.07 2.44-.59 3.19-1.53.57-.72.93-1.65 1.09-2.83.66.4 1.15.92 1.42 1.55.46 1.07.49 2.83-.95 4.26-1.26 1.26-2.78 1.8-5.07 1.82-2.54-.02-4.46-.83-5.71-2.41-1.17-1.48-1.78-3.62-1.8-6.36.02-2.74.63-4.88 1.8-6.36C6.94 3.83 8.86 3.02 11.4 3h.02c2.55.02 4.5.83 5.8 2.42.64.78 1.12 1.76 1.44 2.9l1.74-.46c-.38-1.4-.99-2.62-1.81-3.62C16.92 2.22 14.47 1.18 11.42 1.16h-.03C8.34 1.18 5.92 2.22 4.2 4.27 2.67 6.1 1.88 8.65 1.85 11.84v.02c.03 3.19.82 5.74 2.35 7.57 1.72 2.05 4.14 3.09 7.19 3.11h.03c2.71-.02 4.62-.73 6.19-2.3 2.06-2.05 2-4.63 1.32-6.21-.49-1.13-1.42-2.05-2.7-2.65zm-4.55 5.27c-1.14.06-2.32-.45-2.38-1.55-.04-.81.58-1.72 2.45-1.83.21-.01.42-.02.63-.02.68 0 1.31.07 1.89.19-.22 2.7-1.48 3.16-2.59 3.21z"/></svg>
          </a>
          <a href="https://x.com/theplottv" target="_blank" rel="noopener" aria-label="plot on X" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24h-6.66l-5.214-6.817-5.967 6.817H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.45-6.231zm-1.161 17.52h1.833L7.084 4.126H5.117l11.966 15.644z"/></svg>
          </a>
        </div>
      </div>
    </div>
    <!-- The wordmark: plot in Gabarito Bold outlines (as favicon.svg), each letter
         tracked 20 units tighter, sized to the footer's width so it bleeds off both
         sides and sinks below the bottom edge. -->
    <a class="footer-wordmark" href="/" aria-label="plot home" data-cta="footer">
      <svg viewBox="52 -681 1508 871" aria-hidden="true" focusable="false"><path d="M52 190V-489H161L176 -440Q233 -501 323 -501Q389 -501 440.0 -468.5Q491 -436 519.5 -378.0Q548 -320 548 -244Q548 -169 519.0 -111.0Q490 -53 439.0 -20.5Q388 12 322 12Q249 12 198 -25V190ZM295 -125Q341 -125 370.0 -158.5Q399 -192 399 -244Q399 -297 370.0 -330.5Q341 -364 295 -364Q251 -364 221.0 -330.5Q191 -297 191 -245Q191 -192 221.0 -158.5Q251 -125 295 -125Z"/><path transform="translate(-20,0)" d="M715.0 5Q678.0 5 647.0 -9.5Q616.0 -24 597.0 -56.0Q578.0 -88 578.0 -141V-681H723.0V-193Q723.0 -156 736.5 -145.5Q750.0 -135 771.0 -135V0Q761.0 2 744.5 3.5Q728.0 5 715.0 5Z"/><path transform="translate(-40,0)" d="M1032.0 12Q955.0 12 897.0 -20.5Q839.0 -53 807.0 -111.0Q775.0 -169 775.0 -244Q775.0 -320 807.0 -378.0Q839.0 -436 897.0 -468.5Q955.0 -501 1032.0 -501Q1108.0 -501 1166.0 -468.5Q1224.0 -436 1256.5 -378.0Q1289.0 -320 1289.0 -244Q1289.0 -169 1256.5 -111.0Q1224.0 -53 1166.0 -20.5Q1108.0 12 1032.0 12ZM1032.0 -130Q1080.0 -130 1110.5 -161.5Q1141.0 -193 1141.0 -245Q1141.0 -296 1110.5 -328.0Q1080.0 -360 1032.0 -360Q983.0 -360 953.0 -328.5Q923.0 -297 923.0 -245Q923.0 -193 953.0 -161.5Q983.0 -130 1032.0 -130Z"/><path transform="translate(-60,0)" d="M1539.0 8Q1457.0 8 1411.0 -32.0Q1365.0 -72 1365.0 -163V-355H1289.0V-489H1363.0L1393.0 -607H1511.0V-489H1620.0V-355H1511.0V-195Q1511.0 -161 1527.0 -146.5Q1543.0 -132 1569.0 -132Q1584.0 -132 1597.5 -134.5Q1611.0 -137 1620.0 -140V-3Q1602.0 2 1583.0 5.0Q1564.0 8 1539.0 8Z"/></svg>
    </a>
  </footer>
`;

export const FOOTER_CSS = `
/* Footer — the shared site footer's styles. Single source for every consumer:
   \`npm run footer\` copies this into ui.css (static pages + Storybook) and into
   the marketing-feed and title-page edge functions, which don't load ui.css.
   Edit here, never in a copy.

   Every colour is a theme.css token with its value as the fallback, so the
   footer renders the same on pages that define the tokens under other names.
   The link list is a div with role="navigation", not a <nav>: nav.css styles
   every <nav> as the fixed top bar. Type rules are set in full because pages
   style bare h2 and p. */
.site-footer {
  /* An inline-size container has no intrinsic width, so it must be told to
     fill the row: some pages lay out body as a centred flex column. */
  container-type: inline-size;
  width: 100%;
  box-sizing: border-box;
  position: relative;
  z-index: 3;
  margin-top: -1px;
  overflow: hidden;
  background: var(--bg, #f8f2ea);
  color: var(--ink, #292924);
  border-top: 1px solid rgba(41, 41, 36, 0.12);
  font-family: var(--sans, 'DM Sans', system-ui, sans-serif);
}
.footer-inner {
  max-width: 1360px;
  margin: 0 auto;
  padding: 6rem 2.5rem 0;
}
.footer-top {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 3rem 4rem;
}
.footer-lede {
  margin: 0;
  color: inherit;
  text-align: left;
  font-family: var(--display, 'Gabarito', 'DM Sans', system-ui, sans-serif);
  font-size: clamp(1.55rem, 2.8vw, 2.5rem);
  font-weight: 600;
  line-height: 1.08;
  letter-spacing: -0.03em;
}
.footer-actions {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.5rem 1.25rem;
  margin-top: 1.75rem;
}
.footer-cta {
  display: inline-flex;
  align-items: center;
  min-height: 48px;
  padding: 0 1.5rem;
  border-radius: 9999px;
  background: var(--fill, #ff88c8);
  color: var(--ink, #292924);
  font-size: 0.95rem;
  font-weight: 600;
  text-decoration: none;
  transition: background 0.25s var(--ease, ease), transform 0.25s var(--ease, ease);
}
.footer-cta:hover { background: var(--fill-hover, #ff9fd3); transform: translateY(-1px); }
.footer-login {
  display: inline-flex;
  align-items: center;
  min-height: 48px;
  padding: 0 0.25rem;
  color: var(--ink, #292924);
  font-size: 0.95rem;
  font-weight: 500;
}

.footer-cols {
  display: grid;
  grid-template-columns: repeat(3, auto);
  column-gap: 5rem;
}
.footer-heading {
  margin: 0 0 1rem;
  font-family: var(--sans, 'DM Sans', system-ui, sans-serif);
  font-size: 0.69rem;
  line-height: 1.3;
  font-weight: 600;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--text-secondary, #5f5a52);
}
.footer-col ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.footer-col a {
  color: var(--ink, #292924);
  font-size: 0.95rem;
  line-height: 1.3;
  white-space: nowrap;
}

/* Text links underline in the brand pink on hover and keyboard focus. */
.footer-col a,
.footer-login {
  text-decoration-line: underline;
  text-decoration-thickness: 2px;
  text-underline-offset: 4px;
  text-decoration-color: transparent;
  transition: text-decoration-color 0.2s;
}
.footer-col a:hover,
.footer-col a:focus-visible,
.footer-login:hover,
.footer-login:focus-visible { text-decoration-color: var(--fill, #ff88c8); }

.footer-bottom {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid rgba(41, 41, 36, 0.12);
}
.footer-copy { font-size: 0.8rem; color: var(--text-secondary, #5f5a52); }
.footer-social { display: flex; align-items: center; margin-right: -12px; }
.footer-social a {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  color: var(--ink, #292924);
  transition: color 0.2s;
}
.footer-social a:hover { color: var(--text-secondary, #5f5a52); }
.footer-social svg { width: 19px; height: 19px; display: block; }

/* The wordmark bleeds off both sides and sinks below the bottom edge. The
   SVG is 108% of the footer's width, pulled 4% left; the strip is cropped
   13.9% (of that width) above the letters' baseline, so the edge cuts the
   lower part of p, o and t at every screen size. vw first for browsers
   without container units. */
.footer-wordmark {
  display: block;
  margin-top: 4rem;
  overflow: hidden;
  height: calc(108vw * 681 / 1508 - 13.9vw);
  height: calc(108cqw * 681 / 1508 - 13.9cqw);
}
.footer-wordmark svg {
  display: block;
  width: 108vw;
  width: 108cqw;
  height: auto;
  aspect-ratio: 1508 / 871;
  margin-left: -4vw;
  margin-left: -4cqw;
  fill: var(--surface, #f1e9dc);
  transition: fill 0.3s var(--ease, ease);
}
.footer-wordmark:hover svg { fill: var(--surface-hover, #eadfcf); }
.footer-wordmark:focus-visible { outline: 2px solid var(--ink, #292924); outline-offset: -4px; }

/* Only the pill carries the CSS arrow (ui.css gives every a[data-cta] one;
   defined here too because the edge-function pages don't load ui.css). */
.site-footer a::after { content: none; }
.site-footer .footer-cta::after {
  content: "";
  display: inline-block;
  flex-shrink: 0;
  width: 0.85em;
  height: 0.85em;
  margin-left: 0.4em;
  background: currentColor;
  clip-path: polygon(0 43%, 73% 43%, 43% 13%, 53% 3%, 100% 50%, 53% 97%, 43% 87%, 73% 57%, 0 57%);
  transition: transform 180ms var(--ease, ease);
}
.site-footer .footer-cta:hover::after,
.site-footer .footer-cta:focus-visible::after { transform: rotate(-45deg); }
.footer-cta:focus-visible,
.footer-col a:focus-visible,
.footer-login:focus-visible,
.footer-social a:focus-visible { outline: 2px solid var(--ink, #292924); outline-offset: 2px; border-radius: 4px; }

@media (max-width: 900px) {
  .footer-top { flex-direction: column; align-items: stretch; }
  .footer-cols { column-gap: 3.5rem; }
}
@media (max-width: 600px) {
  .footer-inner { padding: 3.5rem 1.25rem 0; }
  .footer-lede { font-size: 1.55rem; line-height: 1.12; }
  .footer-cols { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 2rem 1rem; }
  .footer-bottom { margin-top: 2.25rem; }
  .footer-wordmark { margin-top: 2rem; }
}
@media (pointer: coarse) {
  .footer-col a { display: inline-flex; align-items: center; min-height: 44px; }
  .footer-col ul { gap: 0; }
}
@media (prefers-reduced-motion: reduce) {
  .footer-cta, .footer-wordmark svg, .site-footer .footer-cta::after { transition: none; }
}
`;
