// @generated by scripts/build-footer.mjs from website/_partials/footer.html
// Do not edit by hand — run `npm run footer` to regenerate.
export const FOOTER_HTML = `
  <footer>
    <div class="footer-inner">
      <a class="footer-logo" href="/">PLOT</a>
      <div class="footer-nav">
        <a href="/" data-cta="footer">Home</a>
        <a href="/whats-on" data-cta="footer">What's On</a>
        <a href="https://app.theplot.tv/login" data-cta="footer">Log in</a>
        <a href="https://app.theplot.tv/signup" data-cta="footer">Sign up</a>
        <a href="/privacy.html" data-cta="footer">Privacy</a>
        <a href="/terms.html" data-cta="footer">Terms</a>
      </div>
      <div class="footer-bottom">
        <div class="footer-copy">&copy; 2026 PLOT</div>
        <div class="footer-social">
          <a href="https://www.instagram.com/theplottv" target="_blank" rel="noopener" aria-label="PLOT on Instagram" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1.1" fill="currentColor" stroke="none"/></svg>
          </a>
          <a href="https://www.threads.net/@theplottv" target="_blank" rel="noopener" aria-label="PLOT on Threads" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M16.05 11.18c-.09-.04-.18-.08-.27-.12-.16-2.93-1.76-4.6-4.45-4.62h-.04c-1.61 0-2.95.69-3.77 1.94l1.48 1.02c.61-.93 1.57-1.13 2.29-1.13h.03c.9.01 1.57.27 2 .78.31.37.52.88.63 1.52-.81-.14-1.69-.18-2.63-.13-2.64.15-4.34 1.69-4.22 3.83.06 1.08.6 2.02 1.51 2.64.77.52 1.77.78 2.8.72 1.37-.07 2.44-.59 3.19-1.53.57-.72.93-1.65 1.09-2.83.66.4 1.15.92 1.42 1.55.46 1.07.49 2.83-.95 4.26-1.26 1.26-2.78 1.8-5.07 1.82-2.54-.02-4.46-.83-5.71-2.41-1.17-1.48-1.78-3.62-1.8-6.36.02-2.74.63-4.88 1.8-6.36C6.94 3.83 8.86 3.02 11.4 3h.02c2.55.02 4.5.83 5.8 2.42.64.78 1.12 1.76 1.44 2.9l1.74-.46c-.38-1.4-.99-2.62-1.81-3.62C16.92 2.22 14.47 1.18 11.42 1.16h-.03C8.34 1.18 5.92 2.22 4.2 4.27 2.67 6.1 1.88 8.65 1.85 11.84v.02c.03 3.19.82 5.74 2.35 7.57 1.72 2.05 4.14 3.09 7.19 3.11h.03c2.71-.02 4.62-.73 6.19-2.3 2.06-2.05 2-4.63 1.32-6.21-.49-1.13-1.42-2.05-2.7-2.65zm-4.55 5.27c-1.14.06-2.32-.45-2.38-1.55-.04-.81.58-1.72 2.45-1.83.21-.01.42-.02.63-.02.68 0 1.31.07 1.89.19-.22 2.7-1.48 3.16-2.59 3.21z"/></svg>
          </a>
          <a href="https://x.com/theplottv" target="_blank" rel="noopener" aria-label="PLOT on X" data-cta="footer-social">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24h-6.66l-5.214-6.817-5.967 6.817H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.45-6.231zm-1.161 17.52h1.833L7.084 4.126H5.117l11.966 15.644z"/></svg>
          </a>
        </div>
      </div>
    </div>
  </footer>
`;
