export const SAMPLE_WATCHED = [
  { title: 'Oppenheimer',                     media_type: 'movie', watched_at: '2025-01-04', rating: 5, mood: 'thoughtful', note: 'Three hours felt like one. The Trinity sequence broke me.' },
  { title: 'Dune: Part Two',                  media_type: 'movie', watched_at: '2025-01-18', rating: 4, mood: 'excited', note: 'Zendaya finally got something to do. Worth the wait.' },
  { title: 'Poor Things',                     media_type: 'movie', watched_at: '2025-01-18', rating: 4, mood: 'weird',        note: 'What on earth did I just watch. I loved it.' },
  { title: 'Killers of the Flower Moon',      media_type: 'movie', watched_at: '2025-02-02', rating: 5, mood: 'sad',          note: 'Lily Gladstone deserved everything.' },
  { title: 'Barbie',                          media_type: 'movie', watched_at: '2025-02-14', rating: 3, mood: 'happy' },
  { title: 'Spider-Man: Across the Spider-Verse', media_type: 'movie', watched_at: '2025-02-14', rating: 5, mood: 'excited',  note: 'The animation is on another level. Genuinely stunned.' },
  { title: 'Saltburn',                        media_type: 'movie', watched_at: '2025-02-28', rating: 4, mood: 'unsettled',    note: 'Did not see that ending coming. Thought about it for days.' },
  { title: 'Past Lives',                      media_type: 'movie', watched_at: '2025-03-08', rating: 5, mood: 'sad',          note: 'Quietly devastating. The airport bench scene.' },
  { title: 'The Holdovers',                   media_type: 'movie', watched_at: '2025-03-22', rating: 4, mood: 'cosy',         note: 'Paul Giamatti doing Paul Giamatti things. Perfect.' },
  { title: 'Anatomy of a Fall',               media_type: 'movie', watched_at: '2025-04-05', rating: 4, mood: 'tense' },
  { name:  'The Last of Us',                  media_type: 'tv',    watched_at: '2025-04-19', rating: 5, mood: 'emotional',    note: 'Episode 3 wrecked me completely.' },
  { name:  'The Bear',                        media_type: 'tv',    watched_at: '2025-05-03', rating: 5, mood: 'stressed' },
  { title: 'Society of the Snow',             media_type: 'movie', watched_at: '2025-05-17', rating: 4, mood: 'intense',      note: 'Had to pause it twice. Brutal and beautiful.' },
  { title: 'American Fiction',               media_type: 'movie', watched_at: '2025-06-01', rating: 4, mood: 'thoughtful' },
  { name:  'Succession',                      media_type: 'tv',    watched_at: '2025-06-21', rating: 5, mood: 'gripped',      note: 'The finale. I need to lie down.' },
  { title: 'Priscilla',                       media_type: 'movie', watched_at: '2025-07-04', rating: 3, mood: 'melancholy' },
  { title: 'The Zone of Interest',            media_type: 'movie', watched_at: '2025-08-09', rating: 5, mood: 'haunted',      note: 'The quietest horror film I\'ve ever seen.' },
  { title: 'May December',                    media_type: 'movie', watched_at: '2025-09-13', rating: 3, mood: 'uncomfortable' },
  { title: 'Migration',                       media_type: 'movie', watched_at: '2025-10-05', rating: 3, mood: 'happy' },
  { name:  'Shōgun',                          media_type: 'tv',    watched_at: '2025-11-02', rating: 5, mood: 'epic',         note: 'Best TV I\'ve seen in years. Hiroyuki Sanada is extraordinary.' },
  { title: 'Inside Out 2',                    media_type: 'movie', watched_at: '2025-11-29', rating: 4, mood: 'emotional' },
  { title: 'Despicable Me 4',                 media_type: 'movie', watched_at: '2025-12-14', rating: 2, mood: 'meh',          note: 'The kids wanted it.' },
  { title: 'Mufasa: The Lion King',           media_type: 'movie', watched_at: '2025-12-26', rating: 3, mood: 'nostalgic' },
  { title: 'Anora',                           media_type: 'movie', watched_at: '2026-01-11', rating: 5, mood: 'shocked',      note: 'That last scene on the kitchen floor. Wow.' },
  { title: 'Conclave',                        media_type: 'movie', watched_at: '2026-01-25', rating: 4, mood: 'tense' },
  { title: 'A Complete Unknown',              media_type: 'movie', watched_at: '2026-02-08', rating: 4, mood: 'inspired',     note: 'Chalamet disappears into it completely.' },
  { title: 'Terrifier 3',                     media_type: 'movie', watched_at: '2026-02-22', rating: 3, mood: 'scared' },
  { name:  'Severance',                       media_type: 'tv',    watched_at: '2026-03-07', rating: 5, mood: 'unsettled',    note: 'My outie and innie both need therapy after this.' },
];

export const GENRES = [
  { key: 'action',      label: 'Action',      movieId: 28,    tvId: 10759, desc: 'Fast-paced and intense.'     },
  { key: 'comedy',      label: 'Comedy',      movieId: 35,    tvId: 35,    desc: 'Laugh-out-loud fun.'         },
  { key: 'drama',       label: 'Drama',       movieId: 18,    tvId: 18,    desc: 'Gripping and emotional.'     },
  { key: 'thriller',    label: 'Thriller',    movieId: 53,    tvId: 53,    desc: 'Suspense and tension.'       },
  { key: 'horror',      label: 'Horror',      movieId: 27,    tvId: 27,    desc: 'Scary and unsettling.'       },
  { key: 'scifi',       label: 'Sci-Fi',      movieId: 878,   tvId: 10765, desc: 'Futuristic and speculative.' },
  { key: 'romance',     label: 'Romance',     movieId: 10749, tvId: 10749, desc: 'Love stories and connection.'},
  { key: 'animation',   label: 'Animation',   movieId: 16,    tvId: 16,    desc: 'Animated worlds.'            },
  { key: 'crime',       label: 'Crime',       movieId: 80,    tvId: 80,    desc: 'Heists, detectives and more.'},
  { key: 'fantasy',     label: 'Fantasy',     movieId: 14,    tvId: 10765, desc: 'Magic and other worlds.'     },
  { key: 'mystery',     label: 'Mystery',     movieId: 9648,  tvId: 9648,  desc: 'Whodunits and big reveals.'  },
  { key: 'documentary', label: 'Documentary', movieId: 99,    tvId: 99,    desc: 'Real stories, real world.'   },
];

export const REGIONS = [
  { code: 'AU', name: 'Australia' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'IE', name: 'Ireland' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'ES', name: 'Spain' },
  { code: 'IT', name: 'Italy' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'IN', name: 'India' },
  { code: 'SG', name: 'Singapore' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'ZA', name: 'South Africa' },
];
