export const GENRES = [
  { key: 'action',      label: 'Action',      movieId: 28,    tvId: 10759, desc: 'Fast-paced and intense.'     },
  { key: 'comedy',      label: 'Comedy',      movieId: 35,    tvId: 35,    desc: 'Laugh-out-loud fun.'         },
  { key: 'drama',       label: 'Drama',       movieId: 18,    tvId: 18,    desc: 'Gripping and emotional.'     },
  { key: 'thriller',    label: 'Thriller',    movieId: 53,    tvId: 53,    desc: 'Suspense and tension.'       },
  { key: 'horror',      label: 'Horror',      movieId: 27,    tvId: 27,    desc: 'Scary and unsettling.'       },
  { key: 'scifi',       label: 'Sci-Fi',      movieId: 878,   tvId: 10765, desc: 'Futuristic and speculative.' },
  { key: 'romance',     label: 'Romance',     movieId: 10749, tvId: 10749, desc: 'Love stories and connection.'},
  { key: 'animation',   label: 'Animation',   movieId: 16,    tvId: 16,    desc: 'Animated worlds.'            },
  { key: 'crime',       label: 'Crime',       movieId: 80,    tvId: 80,    desc: 'Heists, detectives and more.'},
  { key: 'fantasy',     label: 'Fantasy',     movieId: 14,    tvId: 10765, desc: 'Magic and other worlds.'     },
  { key: 'mystery',     label: 'Mystery',     movieId: 9648,  tvId: 9648,  desc: 'Whodunits and big reveals.'  },
  { key: 'documentary', label: 'Documentary', movieId: 99,    tvId: 99,    desc: 'Real stories, real world.'   },
];

export const MOODS = [
  { value: 'happy',         label: 'Happy' },
  { value: 'sad',           label: 'Sad' },
  { value: 'emotional',     label: 'Emotional' },
  { value: 'excited',       label: 'Excited' },
  { value: 'fun',           label: 'Fun' },
  { value: 'tense',         label: 'Tense' },
  { value: 'scared',        label: 'Scared' },
  { value: 'unsettled',     label: 'Unsettled' },
  { value: 'weird',         label: 'Weird' },
  { value: 'cosy',          label: 'Cosy' },
  { value: 'thoughtful',    label: 'Thoughtful' },
  { value: 'inspired',      label: 'Inspired' },
  { value: 'intense',       label: 'Intense' },
  { value: 'stressed',      label: 'Stressed' },
  { value: 'epic',          label: 'Epic' },
  { value: 'haunted',       label: 'Haunted' },
  { value: 'nostalgic',     label: 'Nostalgic' },
  { value: 'melancholy',    label: 'Melancholy' },
  { value: 'gripped',       label: 'Gripped' },
  { value: 'shocked',       label: 'Shocked' },
  { value: 'uncomfortable', label: 'Uncomfortable' },
  { value: 'meh',           label: 'Meh' },
  { value: 'amazing',       label: 'Amazing' },
  { value: 'mindblown',     label: 'Mind Blown' },
];

// Subset shown as quick-pick presets in the log modal
export const PRESET_MOODS = MOODS.filter(m =>
  ['happy', 'sad', 'excited', 'scared', 'thoughtful'].includes(m.value)
);

export const TIMEZONE_TO_REGION = {
  'Australia/': 'AU',        // prefix match handled in timezoneToRegion()
  'America/New_York': 'US',
  'America/Chicago': 'US',
  'America/Los_Angeles': 'US',
  'America/Denver': 'US',
  'America/Phoenix': 'US',
  'Europe/London': 'GB',
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'America/Edmonton': 'CA',
  'America/Winnipeg': 'CA',
  'Pacific/Auckland': 'NZ',
  'Europe/Dublin': 'IE',
  'Europe/Berlin': 'DE',
  'Europe/Paris': 'FR',
  'Europe/Madrid': 'ES',
  'Europe/Rome': 'IT',
  'Europe/Amsterdam': 'NL',
  'Europe/Stockholm': 'SE',
  'Europe/Oslo': 'NO',
  'Europe/Copenhagen': 'DK',
  'Europe/Helsinki': 'FI',
  'Asia/Tokyo': 'JP',
  'Asia/Seoul': 'KR',
  'Asia/Kolkata': 'IN',
  'Asia/Calcutta': 'IN',
  'Asia/Singapore': 'SG',
  'America/Sao_Paulo': 'BR',
  'America/Mexico_City': 'MX',
  'Africa/Johannesburg': 'ZA',
};

export const REGIONS = [
  { code: 'AU', name: 'Australia' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'IE', name: 'Ireland' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'ES', name: 'Spain' },
  { code: 'IT', name: 'Italy' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'IN', name: 'India' },
  { code: 'SG', name: 'Singapore' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'ZA', name: 'South Africa' },
];
