-- Opt-in availability alerts for titles in a user's "My List" watchlist.
-- Delivery records are deliberately separate from notifications: these alerts
-- are generated by a trusted scheduled function, not by a user interaction.
alter table public.profiles
  add column if not exists watchlist_availability_alerts boolean not null default false;

create table if not exists public.watchlist_availability_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  region text not null,
  provider_id integer not null,
  provider_name text not null,
  title text not null,
  notified_at timestamptz not null default now(),
  unique (user_id, tmdb_id, media_type, region, provider_id)
);

create index if not exists watchlist_availability_alerts_user_notified_idx
  on public.watchlist_availability_alerts (user_id, notified_at desc);

alter table public.watchlist_availability_alerts enable row level security;

create policy "own availability alerts readable"
  on public.watchlist_availability_alerts for select
  using (auth.uid() = user_id);
