-- Review/approval statuses for the weekly-batch model:
--   needs_review — generated by the Sunday batch, awaiting admin approval
--   approved     — approved in the admin app; the daily push sends it to Buffer
-- (planned -> copy_ready -> generated -> needs_review -> approved -> published)

ALTER TABLE public.marketing_posts
  DROP CONSTRAINT IF EXISTS marketing_posts_status_check;

ALTER TABLE public.marketing_posts
  ADD CONSTRAINT marketing_posts_status_check CHECK (status IN
    ('planned','copy_ready','generated','needs_review','approved','pending_review',
     'published','partially_published','vetoed','failed','skipped'));
