export const MEDIA_PANEL = {
  talentFallback: 'Talent',
  episodesLoadError: 'Could not load episodes. Try again later.',
  noEpisodesAvailable: 'No episodes available yet.',
  markUnwatched: 'Mark unwatched',
  markWatched: 'Mark watched',
  unmarkAsWatched: 'Unmark as watched',
  markAsWatched: 'Mark as watched',
  couldNotCreateList: 'Could not create the list. Please try again.',
  top10TvShows: 'TV Shows',
  top10Movies: 'Movies',
  currentlyRanked: (rank) => `Currently #${rank}`,
  notRanked: 'Not ranked',
  creating: 'Creating…',
  create: 'Create',
  couldNotUpdateWatchStatus: 'Could not update watch status. Please try again.',
  couldNotClearWatchStatus: 'Could not clear watch status. Please try again.',
  trailerFallback: 'Trailer',
  watching: 'Watching',
  didntFinish: "Didn't finish",
  status: 'Status',
  updating: 'Updating…',
  clearing: 'Clearing…',
  clearStatus: 'Clear status',
  inWatchlist: 'In watchlist',
  addToWatchlist: 'Add to watchlist',
  onList: 'On list',
  list: 'List',
  noRating: 'No rating',
  savingReview: 'Saving review',
  saveChanges: 'Save changes',
  editReview: 'Edit review',
  saveReview: 'Save review',
};
