export const PUBLIC_PROFILE_PAGE = {
  followersTitle: 'Followers',
  followingTitle: 'Following',
  noFollowersYet: 'No followers yet.',
  notFollowingAnyoneYet: 'Not following anyone yet.',
  usernameTaken: 'That username is taken.',
  saveFailed: 'Couldn’t save. Please try again.',
  saving: 'Saving…',
  saveDisplayName: 'Save display name',
  editDisplayName: 'Edit display name',
  saveUsername: 'Save username',
  editUsername: 'Edit username',
  requestToFollow: 'Request to follow',
  follow: 'Follow',
  editProfile: 'Edit profile',
  namePlaceholder: 'Your name',
  bioPlaceholder: 'A little about you',
  verified: 'Verified',
  shareProfile: 'Share profile',
};
